plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/robertsimmons/.openclaw/workspace/website/eb-v2"
publishOrigin = "default"
base = "/Users/robertsimmons/.openclaw/workspace/website/eb-v2"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]